include JTE/Universe/makefile.cfg

OBJS := $(OBJDIR)/JB_Bot.o $(OBJDIR)/JB_Command.o $(OBJDIR)/JB_Game.o \
  $(OBJDIR)/SR_Info.o \
  $(OBJDIR)/JTEMisc.o \
  $(OBJDIR)/DW_World.o \
  $(OBJDIR)/SPM_Player.o $(OBJDIR)/SPM_Command.o \
  $(OBJDIR)/SC_Info.o $(OBJDIR)/SC_HUD.o $(OBJDIR)/SC_Game.o \
  $(OBJDIR)/TML_Game.o \
  $(OBJDIR)/SV_Virus.o \
  $(OBJS)
OPTS := $(OPTS) -DSRB2JTE

$(OBJDIR)/%.o: JTE/%.c
	$(CC) $(CFLAGS) $(WFLAGS) -c $< -o $@
