OBJS := $(OBJDIR)/SU_Game.o \
	$(OBJDIR)/SU_Info.o \
	$(OBJDIR)/SU_Command.o \
	$(OBJDIR)/SU_Save.o \
	$(OBJDIR)/SU_HUD.o \
	$(OBJDIR)/SU_Type.o \
	$(OBJDIR)/SU_Menu.o \
	$(OBJS)

$(OBJDIR)/%.o: JTE/Universe/%.c
	$(CC) $(CFLAGS) $(WFLAGS) -c $< -o $@